[2025-02-28 06:44:03,117] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: simple_dag.hello_task 2025-02-28T06:44:01.179571+00:00 [queued]>
[2025-02-28 06:44:03,134] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: simple_dag.hello_task 2025-02-28T06:44:01.179571+00:00 [queued]>
[2025-02-28 06:44:03,136] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2025-02-28 06:44:03,136] {taskinstance.py:1018} INFO - Starting attempt 1 of 2
[2025-02-28 06:44:03,137] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2025-02-28 06:44:03,150] {taskinstance.py:1038} INFO - Executing <Task(PythonOperator): hello_task> on 2025-02-28T06:44:01.179571+00:00
[2025-02-28 06:44:03,155] {standard_task_runner.py:51} INFO - Started process 1784 to run task
[2025-02-28 06:44:03,158] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'hello_task', '2025-02-28T06:44:01.179571+00:00', '--job-id', '3', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp8s921mw9']
[2025-02-28 06:44:03,162] {standard_task_runner.py:76} INFO - Job 3: Subtask hello_task
[2025-02-28 06:44:03,209] {logging_mixin.py:103} INFO - Running <TaskInstance: simple_dag.hello_task 2025-02-28T06:44:01.179571+00:00 [running]> on host 3981a73a7950
[2025-02-28 06:44:03,266] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=hello_task
AIRFLOW_CTX_EXECUTION_DATE=2025-02-28T06:44:01.179571+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-28T06:44:01.179571+00:00
[2025-02-28 06:44:03,274] {logging_mixin.py:103} INFO - Hello, Airflow!
[2025-02-28 06:44:03,275] {python.py:118} INFO - Done. Returned value was: None
[2025-02-28 06:44:03,287] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=simple_dag, task_id=hello_task, execution_date=20250228T064401, start_date=20250228T064403, end_date=20250228T064403
[2025-02-28 06:44:03,308] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-28 06:44:03,338] {local_task_job.py:118} INFO - Task exited with return code 0
